# Why {#why}

Rena and Crystal are sisters who have a love for being in nature. From hiking, to canoeing, to mushroom hunting, to camping, they have been exploring the outdoors together and in their own lives for many years. And while they have traveled across the United States and abroad, they continue to be amazed at the beauty and wonder that exists in their own home state of Missouri. An often overlooked midwestern state, people forget that Missouri is home to beauty such as Ozark Scenic National Riverways and Mark Twain National Forest. And with every Missouri outdoor location the authors have visited, they've always wanted to share their experience so that others could visit and experience these same spots. This inclination to share was even more heightened by the pandemic this year. So many people began exploring, or wanting to explore, their own states much more, as long-distance travel has been restricted or discouraged. So we write this book so that readers may discover new Missouri locations they may never have heard of and/or when they are looking for somewhere to visit, they can make an educated decision on whether or not it is a good fit for their plans.

