# Southeast {#southeast}

## Elephant Rocks State Park

|Criterion           |Rating:|
|--------------------|-------|
|Beauty              |5    |
|Uncrowded           |4    |
|Ease of navigation  |2    |
|Toddler friendly    |2    |
|Dog friendly        |2    |
|Camping options     |2    |
|Activity options    |4    |


## Johnson Shut-Ins State Park

|Criterion           |Rating:|
|--------------------|-------|
|Beauty              |5    |
|Uncrowded           |1    |
|Ease of navigation  |5    |
|Toddler friendly    |1    |
|Dogs friendly       |2    |
|Camping options     |5    |
|Activity options    |5    |


## Castor River Shut-Ins Conservation Area

|Criterion           |Rating:|
|--------------------|-------|
|Beauty              |4    |
|Uncrowded           |3    |
|Ease of navigation  |3    |
|Toddler friendly    |1    |
|Dogs friendly       |2    |
|Camping options     |1    |
|Activity options    |3    |


## Alley Mill and Spring

|Criterion           |Rating:|
|--------------------|-------|
|Beauty              |5    |
|Uncrowded           |3    |
|Ease of navigation  |5    |
|Toddler friendly    |4    |
|Dogs friendly       |4    |
|Camping options     |2    |
|Activity options    |2    |


## Tom Sauk Mountain State Park

|Criterion           |Rating:|
|--------------------|-------|
|Beauty              |4    |
|Uncrowded           |4    |
|Ease of navigation  |5    |
|Toddler friendly    |5    |
|Dogs friendly       |3    |
|Camping options     |1    |
|Activity options    |1    |